language: bash

templates:
  windows: &windows
    os: windows
    before_script:
      - export PATH="/c/Program Files/CMake/bin":$PATH
  linux: &linux
    os: linux

matrix:  
  include:      
    - name: Windows - MSVC - x64
      <<: *windows
      env: 
        - BUILD_TYPE=Release
        - CMAKE_ARGS="-G \"Visual Studio 15 2017 Win64\""

    - name: Windows - MSVC - x86
      <<: *windows
      env: 
        - BUILD_TYPE=Release
        - CMAKE_ARGS="-G \"Visual Studio 15 2017\""

    - name: Linux - GCC
      <<: *linux
      env:
        - CC=gcc
        - CXX=g++
        - BUILD_TYPE=Release

    - name: Linux - Clang
      <<: *linux
      env:
        - CC=clang
        - CXX=clang++
        - BUILD_TYPE=Release

script:
  - mkdir -p build
  - cd build  
  - cmake ${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - cmake --build .
  - ctest -C ${BUILD_TYPE} --output-on-failure

notifications:
  email: false