language: bash

matrix:  
  include:      
    - name: "Windows - MSVC"
      os: windows      
      install: choco install --force cmake
      env: CMAKE_PATH="/c/Program Files/CMake/bin"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build
  - cd build  
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
  - cmake --build . -- -j10
  - ctest -j10 -C ${BUILD_TYPE} --output-on-failure

notifications:
  email: false

    
