language: bash

matrix:  
  include:      
    - name: "Windows - MSVC"
      os: windows      
      env: PATH="$PATH:/c/Program\ File/CMake/bin/"
    - name: "Linux - GCC"
      os: linux
      env: MATRIX_EVAL="CC=gcc && CXX=g++"
    - name: "Linux - Clang"
      os: linux
      env: MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - export
  - ls /c/Program\ File/CMake/bin/
  - mkdir -p build
  - cd build  
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
  - cmake --build . -- -j10
  - ctest -j10 -C ${BUILD_TYPE} --output-on-failure

notifications:
  email: false

    
