language: bash

templates:
  windows: &windows
    os: windows
    before_script:
      - export PATH="/c/Program Files/CMake/bin":$PATH

  linux: &linux
    os: linux

  osx: &osx
    os: osx

  gcc49: &gcc49
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
          - gcc-4.9    
    x-env: &gcc49-env
      - CC=gcc-4.9
      - CXX=g++-4.9
      - CMAKE_GENERATOR="Unix Makefiles"

  gcc5: &gcc5
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
          - gcc-5    
    x-env: &gcc5-env
      - CC=gcc-5
      - CXX=g++-5
      - CMAKE_GENERATOR="Unix Makefiles"

  gcc49: &gcc7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - gcc-7    
    x-env: &gcc7-env
      - CC=gcc-7
      - CXX=g++-7
      - CMAKE_GENERATOR="Unix Makefiles"


matrix:  
  include:      
    - name: Windows - MSVC - x64
      <<: *windows
      env: 
        - CMAKE_BUILD_TYPE=Release
        - CMAKE_GENERATOR="Visual Studio 15 2017 Win64"

    - name: Windows - MSVC - x86
      <<: *windows
      env: 
        - CMAKE_BUILD_TYPE=Release
        - CMAKE_GENERATOR="Visual Studio 15 2017"

    - name: Linux - GCC4.9 - x64
      <<: *linux
      <<: *gcc49
      env:
        <<: *gcc49-env
        - CMAKE_BUILD_TYPE=Release

    - name: Linux - GCC5 - x64
      <<: *linux
      <<: *gcc5
      env:
        <<: *gcc5-env
        - CMAKE_BUILD_TYPE=Release

    - name: Linux - GCC7 - x64
      <<: *linux
      env:
        <<: *gcc7-env
        - CMAKE_BUILD_TYPE=Release

    - name: Linux - Clang - x64
      <<: *linux
      env:
        - CC=clang
        - CXX=clang++
        - CMAKE_BUILD_TYPE=Release
        - CMAKE_GENERATOR="Unix Makefiles"

    - name: OS-X - Clang - x64
      <<: *osx
      env:
        - CMAKE_BUILD_TYPE=Release
        - CMAKE_GENERATOR="Unix Makefiles"

script:
  - mkdir -p build
  - cd build  
  - cmake -G "${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - cmake --build .
  - ctest --output-on-failure

notifications:
  email: false