language: bash

templates:
  windows: &windows
    os: windows
    before_script:
      - export PATH="/c/Program Files/CMake/bin":$PATH
  linux: &linux
    os: linux
  osx: &osx
    os: osx

  release:
    env+:
      - CMAKE_BUILD_TYPE=Release
      


matrix:  
  include:      
    - name: Windows - MSVC - x64
      <<: *windows
      <<: *release
      env: 
        - CMAKE_GENERATOR="Visual Studio 15 2017 Win64"

    - name: Windows - MSVC - x86
      <<: *windows
      <<: *release
      env:
        - CMAKE_GENERATOR="Visual Studio 15 2017"

    - name: Linux - GCC - x64
      <<: *linux
      <<: *release
      env:
        - CC=gcc
        - CXX=g++
        - CMAKE_GENERATOR="Unix Makefiles"

    - name: Linux - Clang - x64
      <<: *linux
      <<: *release
      env:
        - CC=clang
        - CXX=clang++
        - CMAKE_GENERATOR="Unix Makefiles"

    - name: OS-X - Clang - x64
      <<: *osx
      <<: *release
      env:
        - CMAKE_GENERATOR="Unix Makefiles"

script:
  - mkdir -p build
  - cd build  
  - cmake -G "${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - cmake --build .
  - ctest --output-on-failure

notifications:
  email: false