language: bash

templates:
  release: &release
    env: &release-env
      - CMAKE_BUILD_TYPE=Release
  
  debug: &debug
    env: &debug-env
      - CMAKE_BUILD_TYPE=Debug

  linux: &linux
    os: linux
    env: &linux-env
      - CMAKE_GENERATOR="Unix Makefiles"
    gcc-4.9: &gcc-49      
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: [ g++-4.9, gcc-4.9 ]
      env: &gcc-49-env
        - CC=gcc-4.9
        - CXX=g++-4.9        
    gcc-5: &gcc-5
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: [ g++-5, gcc-5 ]
        env: &gcc-5-env
          - CC=gcc-5
          - CXX=g++-5
    gcc-7: &gcc-7
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: [ g++-7, gcc-7 ]
        env: &gcc-7-env
          - CC=gcc-7
          - CXX=g++-7
    clang:
      env: &clang-env
        - CC=clang
        - CXX=clang++

            
  windows: &windows
    os: windows
    env: &windows-env
      - CMAKE_BUILD_CMD_ARGS="/nologo /verbosity:normal"
    before_script:
      - export PATH="/c/Program Files/CMake/bin":$PATH
    msvc15-x64: &msvc15-x64
      env: &msvc15-x64-env
        - CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
    msvc15-x86: &msvc15-x86
      env: &msvc15-x86-env
        - CMAKE_GENERATOR="Visual Studio 15 2017"

  osx: &osx
    os: osx
    env: &osx-env
      - CMAKE_GENERATOR="Unix Makefiles"      

matrix:  
  include:      
    - name: "Windows - MSVC15 - x64 - Release"
      <<: *windows
      <<: *msvc15-x64
      <<: *release
      env: [ *windows-env, *release-env, *msvc15-x64-env ] 

    - name: "Windows - MSVC15 - x86 - Release"
      <<: *windows
      <<: *msvc15-x86
      <<: *release
      env: [ *windows-env, *release-env, *msvc15-x86-env ] 

    - name: "Windows - MSVC15 - x64 - Debug"
      <<: *windows
      <<: *msvc15-x64
      <<: *debug
      env: [ *windows-env, *debug-env, *msvc15-x64-env ] 

    - name: "Windows - MSVC15 - x86 - Debug"
      <<: *windows
      <<: *msvc15-x86
      <<: *release
      env: [ *windows-env, *debug-env, *msvc15-x86-env ] 

    - <<: *linux
      <<: *gcc-49
      <<: *release
      env: [ *linux-env, *release-env, *gcc-49-env ]

    - <<: *linux
      <<: *gcc-5
      <<: *release
      env: [ *linux-env, *release-env, *gcc-5-env ]

    - <<: *linux
      <<: *gcc-7
      <<: *release
      env: [ *linux-env, *release-env, *gcc-7-env ]

    - <<: *linux      
      env: [ *linux-env, *release-env, *clang-env ]

    - <<: *osx
      env: [ *osx-env, *release-env ]

script:
  - mkdir -p build
  - cd build  
  - cmake -G "${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - cmake --build . --config ${CMAKE_BUILD_TYPE} -- ${CMAKE_BUILD_ARGS}
  - ctest --output-on-failure

notifications:
  email: false