language: bash

templates:
  gcc-4.9: &gcc-49      
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: [ g++-4.9, gcc-4.9 ]
  gcc-5: &gcc-5
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: [ g++-5, gcc-5 ]
  gcc-6: &gcc-6
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: [ g++-6, gcc-6 ]
  gcc-7: &gcc-7
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: [ g++-7, gcc-7 ]
  gcc-8: &gcc-8
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: [ g++-8, gcc-8 ]
          
  windows: &windows
    os: windows
    before_script:
      - export PATH="/c/Program Files/CMake/bin":$PATH      

matrix:  
  include: 

    ###########################################################################
    # Clang on OSX
    ###########################################################################

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles"
      os: osx
      osx_image: xcode10

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" 
      os: osx
      osx_image: xcode9.4

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" 
      os: osx
      osx_image: xcode8.3

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" 
      os: osx
      osx_image: xcode7.3

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" 
      os: osx
      osx_image: xcode6.4

    ###########################################################################
    # GCC on Linux
    ###########################################################################

    - env: CXX=g++-4.9 CC=gcc-4.9 GENERATOR="Unix Makefiles"
      os: linux
      <<: *gcc-49
      
    - env: CXX=g++-5 CC=gcc-5 GENERATOR="Unix Makefiles"
      os: linux
      <<: *gcc-5
      
    - env: CXX=g++-6 CC=gcc-6 GENERATOR="Unix Makefiles"
      os: linux
      <<: *gcc-6
      
    - env: CXX=g++-7 CC=gcc-7 GENERATOR="Unix Makefiles"
      os: linux
      <<: *gcc-7
      
    - env: CXX=g++-8 CC=gcc-8 GENERATOR="Unix Makefiles"
      os: linux
      <<: *gcc-8
      
    ###########################################################################
    # Clang on Linux
    ###########################################################################

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles"
      os: linux

    # TODO(cme): cover clang multiple version

    ###########################################################################
    # MSVC on Windows
    ###########################################################################

    - env: GENERATOR="Visual Studio 15 2017 Win64"
      <<: *windows

    - env: GENERATOR="Visual Studio 15 2017"
      <<: *windows

    ###########################################################################
    # Clang on Windows
    ###########################################################################

    # TODO(cme): do it

script:
  ###########################################################################
  # Debug
  ###########################################################################
  - mkdir -p build/Debug
  - cd build/Debug
  - cmake -G "${GENERATOR}" -DCMAKE_BUILD_BUILD=Debug ../../
  - cmake --build . --config Debug
  - ctest --output-on-failure

  ###########################################################################
  # Release
  ###########################################################################
  - mkdir -p build/Release
  - cd build/Release
  - cmake -G "${GENERATOR}" -DCMAKE_BUILD_BUILD=Release ../../
  - cmake --build . --config Release
  - ctest --output-on-failure

notifications:
  email: false