language: bash

matrix:
  include:  
    ## Windows
    - os: windows
      env: MATRIX_EVAL="BUILD_TYPE=Release"

    ## Windows
    - os: windows
      env: MATRIX_EVAL="BUILD_TYPE=Debug"


before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build
  - cd build  
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
  - cmake --build . -- -j10
  - ctest -j10 -C ${BUILD_TYPE} --output-on-failure

notifications:
  email: false

    
