language: bash

matrix:  
  include:      
    - name: "Windows - MSVC"
      os: windows      
      env: 
        - CMAKE_PATH="/c/Program Files/CMake/bin"
        - BUILD_TYPE=Release
      before_script:
        - export PATH=$CMAKE_PATH:$PATH
    - name: "Linux - GCC"
      os: linux
      env:
        - CC=gcc
        - CXX=g++
        - BUILD_TYPE=Release
    - name: "Linux - Clang"
      os: linux
      env:
        - CC=clang
        - CXX=clang++
        - BUILD_TYPE=Release
        
script:
  - mkdir -p build
  - cd build  
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - cmake --build .
  - ctest -C ${BUILD_TYPE} --output-on-failure

notifications:
  email: false

    
