language: bash

matrix:
  include:      
    - name: "Windows - MSVC - Release"
      os: windows
      install: choco install --force cmake.install --installargs '"ADD_CMAKE_TO_PATH=User"'
      env: MATRIX_EVAL="BUILD_TYPE=Release"
    
    - name: "Windows - MSVC - Debug"
      os: windows
      install: choco install --force cmake.install --installargs '"ADD_CMAKE_TO_PATH=User"'
      env: MATRIX_EVAL="BUILD_TYPE=Debug"


before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build
  - cd build  
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
  - cmake --build . -- -j10
  - ctest -j10 -C ${BUILD_TYPE} --output-on-failure

notifications:
  email: false

    
