language: bash

templates:
  release: &release
    env: &release-env
      - BUILD=Release
  
  debug: &debug
    env: &debug-env
      - BUILD=Debug

  gcc-4.9: &gcc-49      
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: [ g++-4.9, gcc-4.9 ]
  gcc-5: &gcc-5
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: [ g++-5, gcc-5 ]
  gcc-6: &gcc-6
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: [ g++-6, gcc-6 ]
  gcc-7: &gcc-7
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: [ g++-7, gcc-7 ]
  gcc-8: &gcc-8
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: [ g++-8, gcc-8 ]
          
  windows: &windows
    os: windows
    env: &windows-env
      - BUILD_ARGS="/nologo /verbosity:normal"
    before_script:
      - export PATH="/c/Program Files/CMake/bin":$PATH
    msvc15-x64: &msvc15-x64
      env: &msvc15-x64-env
        - GENERATOR="Visual Studio 15 2017 Win64"
    msvc15-x86: &msvc15-x86
      env: &msvc15-x86-env
        - GENERATOR="Visual Studio 15 2017"    

matrix:  
  include: 

    ###########################################################################
    # Clang on OSX
    ###########################################################################

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Release
      os: osx
      osx_image: xcode10

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Debug
      os: osx
      osx_image: xcode10

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Release
      os: osx
      osx_image: xcode9.4

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Debug
      os: osx
      osx_image: xcode9.4

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Release
      os: osx
      osx_image: xcode8.3

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Debug
      os: osx
      osx_image: xcode8.3

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Release
      os: osx
      osx_image: xcode7.3

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Debug
      os: osx
      osx_image: xcode7.3

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Release
      os: osx
      osx_image: xcode6.4

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Debug
      os: osx
      osx_image: xcode6.4

    ###########################################################################
    # GCC on Linux
    ###########################################################################

    - env: CXX=g++-4.9 CC=gcc-4.9 GENERATOR="Unix Makefiles" BUILD=Release
      os: linux
      <<: *gcc-49
      
    - env: CXX=g++-4.9 CC=gcc-4.9 GENERATOR="Unix Makefiles" BUILD=Debug
      os: linux
      <<: *gcc-49
      
    - env: CXX=g++-5 CC=gcc-5 GENERATOR="Unix Makefiles" BUILD=Release
      os: linux
      <<: *gcc-5
      
    - env: CXX=g++-5 CC=gcc-5 GENERATOR="Unix Makefiles" BUILD=Debug
      os: linux
      <<: *gcc-5

    - env: CXX=g++-6 CC=gcc-6 GENERATOR="Unix Makefiles" BUILD=Release
      os: linux
      <<: *gcc-6
      
    - env: CXX=g++-6 CC=gcc-6 GENERATOR="Unix Makefiles" BUILD=Debug
      os: linux
      <<: *gcc-6

    - env: CXX=g++-7 CC=gcc-7 GENERATOR="Unix Makefiles" BUILD=Release
      os: linux
      <<: *gcc-7
      
    - env: CXX=g++-7 CC=gcc-7 GENERATOR="Unix Makefiles" BUILD=Debug
      os: linux
      <<: *gcc-7

    - env: CXX=g++-8 CC=gcc-8 GENERATOR="Unix Makefiles" BUILD=Release
      os: linux
      <<: *gcc-8
      
    - env: CXX=g++-8 CC=gcc-8 GENERATOR="Unix Makefiles" BUILD=Debug
      os: linux
      <<: *gcc-8

    ###########################################################################
    # Clang on Linux
    ###########################################################################

    - env: CXX=clang CC=clang++ GENERATOR="Unix Makefiles" BUILD=Release
      os: linux

    - env: CXX=clang CC=clang++ GENERATOR="Unix Makefiles" BUILD=Debug
      os: linux

    ###########################################################################
    # MSVC on Windows
    ###########################################################################

    - name: "Windows - MSVC15 - x64 - Release"
      <<: *windows
      <<: *msvc15-x64
      <<: *release
      env: [ *windows-env, *release-env, *msvc15-x64-env ] 

    - name: "Windows - MSVC15 - x64 - Debug"
      <<: *windows
      <<: *msvc15-x64
      <<: *debug
      env: [ *windows-env, *debug-env, *msvc15-x64-env ] 

    - name: "Windows - MSVC15 - x86 - Release"
      <<: *windows
      <<: *msvc15-x86
      <<: *release
      env: [ *windows-env, *release-env, *msvc15-x86-env ] 

    - name: "Windows - MSVC15 - x86 - Debug"
      <<: *windows
      <<: *msvc15-x86
      <<: *release
      env: [ *windows-env, *debug-env, *msvc15-x86-env ] 

script:
  - mkdir -p build
  - cd build  
  - cmake -G "${GENERATOR}" -DCMAKE_BUILD_BUILD=${BUILD} ..
  - cmake --build . --config ${BUILD} -- ${BUILD_ARGS}
  - ctest --output-on-failure

notifications:
  email: false