language: bash

templates:
  release: &release
    env: &release-env
      - BUILD=Release
  
  debug: &debug
    env: &debug-env
      - BUILD=Debug

  linux: &linux
    os: linux
    env: &linux-env
      - GENERATOR="Unix Makefiles"
    gcc-4.9: &gcc-49      
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: [ g++-4.9, gcc-4.9 ]
      env: &gcc-49-env
        - CC=gcc-4.9
        - CXX=g++-4.9        
    gcc-5: &gcc-5
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: [ g++-5, gcc-5 ]
        env: &gcc-5-env
          - CC=gcc-5
          - CXX=g++-5
    gcc-6: &gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: [ g++-6, gcc-6 ]
        env: &gcc-7-env
          - CC=gcc-6
          - CXX=g++-6
    gcc-7: &gcc-7
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: [ g++-7, gcc-7 ]
        env: &gcc-7-env
          - CC=gcc-7
          - CXX=g++-7
    gcc-8: &gcc-8
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: [ g++-8, gcc-8 ]
        env: &gcc-7-env
          - CC=gcc-8
          - CXX=g++-8
    clang:
      env: &clang-env
        - CC=clang
        - CXX=clang++

            
  windows: &windows
    os: windows
    env: &windows-env
      - CMAKE_BUILD_CMD_ARGS="/nologo /verbosity:normal"
    before_script:
      - export PATH="/c/Program Files/CMake/bin":$PATH
    msvc15-x64: &msvc15-x64
      env: &msvc15-x64-env
        - GENERATOR="Visual Studio 15 2017 Win64"
    msvc15-x86: &msvc15-x86
      env: &msvc15-x86-env
        - GENERATOR="Visual Studio 15 2017"    

matrix:  
  include: 

    ###########################################################################
    # Clang on OSX
    ###########################################################################

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Release
      os: osx
      osx_image: xcode10

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Debug"
      os: osx
      osx_image: xcode10

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Release
      os: osx
      osx_image: xcode9.4

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Debug"
      os: osx
      osx_image: xcode9.4

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Release
      os: osx
      osx_image: xcode8.3

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Debug"
      os: osx
      osx_image: xcode8.3

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Release
      os: osx
      osx_image: xcode7.3

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Debug"
      os: osx
      osx_image: xcode7.3

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Release
      os: osx
      osx_image: xcode6.4

    - env: CXX=clang++ CC=clang GENERATOR="Unix Makefiles" BUILD=Debug"
      os: osx
      osx_image: xcode6.4

    ###########################################################################
    # MSVC on Windows
    ###########################################################################

    - name: "Windows - MSVC15 - x64 - Release"
      <<: *windows
      <<: *msvc15-x64
      <<: *release
      env: [ *windows-env, *release-env, *msvc15-x64-env ] 

    - name: "Windows - MSVC15 - x64 - Debug"
      <<: *windows
      <<: *msvc15-x64
      <<: *debug
      env: [ *windows-env, *debug-env, *msvc15-x64-env ] 

    - name: "Windows - MSVC15 - x86 - Release"
      <<: *windows
      <<: *msvc15-x86
      <<: *release
      env: [ *windows-env, *release-env, *msvc15-x86-env ] 

    - name: "Windows - MSVC15 - x86 - Debug"
      <<: *windows
      <<: *msvc15-x86
      <<: *release
      env: [ *windows-env, *debug-env, *msvc15-x86-env ] 

    - name: "Linux - GCC 4.9 - x64 - Release"
      <<: *linux
      <<: *gcc-49
      <<: *release
      env: [ *linux-env, *release-env, *gcc-49-env ]

    - name: "Linux - GCC 5 - x64 - Release"
      <<: *linux
      <<: *gcc-5
      <<: *release
      env: [ *linux-env, *release-env, *gcc-5-env ]

    - name: "Linux - GCC 6 - x64 - Release"
      <<: *linux
      <<: *gcc-6
      <<: *release
      env: [ *linux-env, *release-env, *gcc-6-env ]

    - name: "Linux - GCC 7 - x64 - Release"    
      <<: *linux
      <<: *gcc-7
      <<: *release
      env: [ *linux-env, *release-env, *gcc-7-env ]

    - name: "Linux - GCC 8 - x64 - Release"    
      <<: *linux
      <<: *gcc-8
      <<: *release
      env: [ *linux-env, *release-env, *gcc-8-env ]

    - name: "Linux - Clang - x64 - Release"
      <<: *linux    
      <<: *release
      env: [ *linux-env, *release-env, *clang-env ]

    - name: "Linux - Clang - x64 - Debug"
      <<: *linux    
      <<: *debug
      env: [ *linux-env, *debug-env, *clang-env ]

script:
  - mkdir -p build
  - cd build  
  - cmake -G "${GENERATOR}" -DCMAKE_BUILD_BUILD=${BUILD} ..
  - cmake --build . --config ${BUILD} -- ${CMAKE_BUILD_ARGS}
  - ctest --output-on-failure

notifications:
  email: false