language: bash

matrix:
  env:
    - MATRIX_EVAL="BUILD_TYPE=Debug"
    - MATRIX_EVAL="BUILD_TYPE=Release"
  include:      
    - name: "Windows - MSVC"
      os: windows      
      env: PATH=C:\Program Files\CMake\bin;%PATH%

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build
  - cd build  
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
  - cmake --build . -- -j10
  - ctest -j10 -C ${BUILD_TYPE} --output-on-failure

notifications:
  email: false

    
