language: cpp

matrix:
  include:
    # Linux (GCC)
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # OSX (GCC)
    - os: osx
          osx_image: xcode8
          env:
            - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

        - os: osx
          osx_image: xcode8
          env:
            - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

        - os: osx
          osx_image: xcode8
          env:
            - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"


before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make -j 4

notifications:
  email: false