language: bash

templates:
  release: &release
    env: &release-env
      - CMAKE_BUILD_TYPE=Release
  
  debug: &debug
    env: &debug-env
      - CMAKE_BUILD_TYPE=Debug

  linux: &linux
    os: linux
    sources:
      - ubuntu-toolchain-r-test
    env: &linux-env
      - CMAKE_GENERATOR="Unix Makefiles"
    gcc-4.9: &gcc-49
        packages:
          - g++-4.9
          - gcc-4.9
        env: &gcc-49-env
          - CC=gcc-4.9
          - CXX=g++-4.9
    gcc-5: &gcc-5
        packages:
          - g++-5
          - gcc-5
        env: &gcc-5-env
          - CC=gcc-5
          - CXX=g++-5
    gcc-7: &gcc-7
        packages:
          - g++-7
          - gcc-7
        env: &gcc-7-env
          - CC=gcc-7
          - CXX=g++-7
        
    
  windows: &windows
    os: windows
    env: &windows-env
    before_script:
      - export PATH="/c/Program Files/CMake/bin":$PATH
    msvc15-x64: &msvc15-x64
      env: &msvc15-x64-env
        - CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
    msvc15-x86: &msvc15-x86
      env: &msvc15-x86-env
        - CMAKE_GENERATOR="Visual Studio 15 2017"

  osx: &osx
    os: osx

matrix:  
  include:      
    - name: Windows - MSVC - Release - x64
      <<: *windows
      <<: *msvc15-x64
      <<: *release
      env: [ *windows-env, *release-env, *msvc15-x64-env ] 

    - name: Windows - MSVC - Release - x86
      <<: *windows
      <<: *msvc15-x86
      <<: *release
      env: [ *windows-env, *release-env, *msvc15-x86-env ] 

    - name: Linux - GCC4.9 - Release - x64
      <<: *linux
      <<: *gcc-49
      <<: *release
      env: [ *linux-env, *release-env, *gcc-49-env ]

    - name: Linux - GCC5 - Release - x64
      <<: *linux
      <<: *gcc-5
      <<: *release
      env: [ *linux-env, *release-env, *gcc-5-env ]

    - name: Linux - GCC7 - Release - x64
      <<: *linux
      <<: *gcc-7
      <<: *release
      env: [ *linux-env, *release-env, *gcc-7-env ]

    - name: Linux - Clang - x64
      <<: *linux
      env:
        - CC=clang
        - CXX=clang++
        - CMAKE_BUILD_TYPE=Release
        - CMAKE_GENERATOR="Unix Makefiles"

    - name: OS-X - Clang - x64
      <<: *osx
      env:
        - CMAKE_BUILD_TYPE=Release
        - CMAKE_GENERATOR="Unix Makefiles"

script:
  - mkdir -p build
  - cd build  
  - cmake -G "${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - cmake --build .
  - ctest --output-on-failure

notifications:
  email: false